### PR TITLE
Set a basic directory structure

### PR DESCRIPTION
**Pull request by MonsJovis**

### CODE REVIEW

**Comment by Fabsi110** [comment]
I just discovered that I cannot merge this pull request. Looks like not everybody has write access?!

**Comment by MonsJovis** [comment]
oh yeah! now I've remove myself from the collaborators instead of adding all... =)))

@lauritzthamsen could you add us all as collaborators to the repo?

**Comment by lauritzthamsen** [comment]
i think collaborators is for adding people who are not part of the organization. having all in a team with write access should be the way to go.

**Comment by lauritzthamsen** [comment]
if you want i can set the default access options for all repos of this organziation from `read` to `write` or `admin`. then every member of the organization would be able to read and write every repository.

**Comment by Fabsi110** [comment]
write access should be perfectly fine I think... Thank you!

**Comment by lauritzthamsen** [comment]
ok, now everybody has write access to everything. let me know, if you want to change that again.

**Pull request merged**
